name: Check that version has been updated
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
jobs:
  version_updated:
    name: Bump version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify Versions Updated
        uses: tj-actions/changed-files@v41
        id: verify_changed_files
        with:
          files: |
             VERSION
      - name: Fail Unless Versions Updated
        id: fail_unless_changed
        if: steps.verify_changed_files.outputs.any_changed == 'false'
        run: |
              echo "::error ::Please update the VERSION file"
              exit 1
